### PR TITLE
Support for ssl redis server

### PR DESCRIPTION
**Pull request by kpbochenek**

### CODE REVIEW

**Comment by jastice** [comment]
Looks like the tests still need to be updated :)
Btw, I might not be reviewing these on time, so you want to merge yourself at your discretion.

**Comment by indusbull** [comment]
Is there any plan to merge this PR?

**Comment by kpbochenek** [comment]
Hi! In my project I used stunnel and suspended work on direct ssl support, but if there is an interest in that I could try and finish those changes. It requires update of tests but also still some code changes. I am currently on holiday buy can pick up this topic at the end of next week.

**Comment by indusbull** [comment]
Can you provide more details on how are you using this library with stunnel? Are you connecting to AWS ElasticCache for Redis **Cluster**? If yes, are you connecting to AWS Endpoint for using RedisCluster() api or Redis()? How is your stunnel connfigured to work with scredis?

**Comment by jeberdson** [comment]
can you merge this PR and release?
I am searching for a redis client which supports SSL connections for my Play Scala application.
But seems no library written in Scala supports it :(

**Comment by kpbochenek** [comment]
I am on it, I need to review what changed but I will try to merge it and release this week

**Comment by rtehok** [comment]
Hello, any chance this could be fixed and merged?
We are also trying to use scredis to connect to elasticache with encryption at-transit.

Thanks!

**Comment by kpbochenek** [comment]
This is too outdated and with a new akka version interface changed so it is better to start over adding support for ssl.

**Pull request closed without merging**
