### PR TITLE
Implement stream commands

### PR DESCRIPTION
**Pull request by kardapoltsev**
It's still WIP but I have two questions before pushing other commands.
1. Am I going to the right direction? Are you ok with the code?
2. Do you have any code style (formatting) settings/guides/etc?

### CODE REVIEW

**Comment by kpbochenek** [comment]
Thanks for work in this direction! will take a look shortly :+1:

**Comment by kpbochenek** [comment]
Yes a direction for those commands you mentioned is correct, they are very similar to the ones already implemented.
The problem might be more with XREAD.
Not sure yet if it can be handled as standard command or as something similar to PubSub that it would require dedicated connection channel.

I am formatting code by standard intellij rules but there are no code style guides for this project.

**Comment by kardapoltsev** [comment]
>> The problem might be more with XREAD.

**Comment by kardapoltsev** [comment]
Hi @kpbochenek! 
Could you please take a look at this implementation please? It doesn't include stream commands related to consumer group yet but I'll definitly add them in the next PR.

**Comment by kardapoltsev** [comment]
Any updates?

**Comment by jastice** [comment]
Since apparently there is no active maintainer of this repository - would you like to become one @alexeykardapoltsev-cb ?

**Comment by kardapoltsev** [comment]
> Since apparently there is no active maintainer of this repository - would you like to become one @alexeykardapoltsev-cb ?

Yes, I would. Now I have some free time and interested in thing project

**Comment by jastice** [comment]
Great, I've invited you :)

**Comment by kardapoltsev** [comment]
Sorry, @jastice could you resend an invitation please?

**Comment by jastice** [comment]
done

**Pull request closed without merging**
