### PR TITLE
A few small fixes

### PR DESCRIPTION
**Pull request by avistramer**
Hi team - Great library, we've enjoyed using it for a while now! Wanted to contribute back some fixes we've applied to our fork.

1. In `RedisCluster`, pass the `tcpSendBufferSizeHint` and `tcpReceiveBufferSizeHint` arguments through correctly.
2. Reduce the `maxHashMisses` in `ClusterConnection` before refreshing node info. The old value of `100` can lead to significant time with stale info.
3. `ClusterConnection.delayed()` was ignoring the delay argument passed in.
4. When a cluster is in the middle of migrating a slot, on the source node the slot info might look like `[1129->-0af60d4b8d978d56f1d2b9f2f7ceb20fc43ecf01]` (i.e. a MIGRATING state) and on the destination like `[1129-<-0d704fe2d201af3c44ca23b0aef99a2dd5fd9222]` (i.e. an IMPORTING state). This is instead of the typical valid number or range of numbers. This breaks `ClusterRequests.parseClusterNode()` when it does `s.toLong`. I believe the right thing to do here is to ignore any slot that is in an IMPORTING state but still consider a slot in a MIGRATING state as part of the node. The code reflects that now.

### CODE REVIEW

**Comment by kpbochenek** [comment]
Those are very good catches, thanks for contributing!

could you try expose `private val maxHashMisses` as configuration parameter with default value 10?
If it causes any problems for current users it will only be a matter of changing configuration and no need to do additional release.

Other changes look good :+1:

**Comment by avistramer** [comment]
Makes perfect sense. `maxHashMisses` is now exposed as a configuration parameter with default value 10.

**Comment by kpbochenek** [comment]
Looking good, thanks!

**Comment by kpbochenek** [comment]
Should be available in 2.3.4 version (needs a while to sync to mvn central)

**Pull request merged**
