### PR TITLE
Add SMISMEMBER command

### PR DESCRIPTION
**Pull request by Philippus**
Applying this PR will add the SMISMEMBER command, which was introduced in Redis 6.2. I didn't add the tests yet, because I think that requires some work on the CI build first.

### CODE REVIEW

**Comment by jastice** [comment]
Thanks for the PR. Unfortunately at the moment it looks like there's no active maintainer of this repo. Are you interested in this role @Philippus ?

**Comment by Philippus** [comment]
Yes, I'm interested.

**Comment by jastice** [comment]
Great! I've added you as maintainer for now.

**Comment by kardapoltsev** [comment]
@Philippus could you please add a simple test for new command?

**Comment by Philippus** [comment]
I added a test.

**Comment by Philippus** [comment]
Can you have another look @kardapoltsev ?

**Pull request merged**
