### PR TITLE
Cross-build for Scala 2.12

### LINKED ISSUE #23: Scala 2.12
Would it be possible to compile this lib against Scala 2.12? It has been already release. Could you publish those artifacts into maven repository?

Thanks!

### PR DESCRIPTION
**Pull request by maxcom**
fixes #23

### CODE REVIEW

**Comment by jastice** [comment]
Thanks a lot!

**Comment by maxcom** [comment]
Please release build with 2.12 support.

**Comment by twistedpair** [comment]
@jastice any plans to release this 2.12 build?

**Comment by jastice** [comment]
@twistedpair I'll try to get around to it this weekend. If somebody is willing to take care of it more regularly, please let me know and I'll add you to the org.

**Comment by majk-p** [comment]
@jastice Any chances for release?

**Comment by jastice** [comment]
I'm a bit late, but... there's continuous releases to bintray for now:
https://bintray.com/jastice/maven/scredis/

```
resolvers += Resolver.bintrayIvyRepo("jastice","maven")
libraryDependencies += "com.github.scredis" %% "scredis" % "<version>"
```

**Pull request merged**
